spring:
  application:
    name: vevor-sofaboot
  profiles:
    active: dev

#logging path
logging:
  path: D:\sofaboot\log

com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://127.0.0.1:8848
