spring:
  application:
    name: vevor-sofaboot
  profiles:
    active: dev
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  #数据源连接池配置
  datasource:
    #连接MySql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-uf60h3y70qn9imwdaio.mysql.rds.aliyuncs.com:3306/jerveen?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
    username: vevor
    password: sanvn!@#123
    driverClassName: com.mysql.cj.jdbc.Driver
    #Druid连接配置
    initialSize: 20
    minIdle: 20
    maxActive: 30
    maxWait: 100000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select now()
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    keepAlive: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    resetEnable: true
    logAbandoned: true
    removeAbandoned: true
    removeAbandonedTimeout: 180000

  #Jpa配置
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

server:
  port: 8090

#logging path
logging:
  path: D:\sofaboot\log

#Logback日志路径
logback:
  logdir: D:\sofaboot\logback

#服务注册中心
com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://127.0.0.1:8848
        bolt-port: 2200
      #tracer数据上报的服务端zipkin地址
      tracer:
        zipkin:
          base-url: http://47.103.124.72:9411
      #添加metrics数据上报的服务端地址
      lookout:
        agent-host-address: 127.0.0.1
        exporter-enable: true